import React from 'react'
import Head from 'next/head'
import Editor from '../components/Editor'
import Preview from '../components/Preview'

export default function Home() {
  const [doc, setDoc] = React.useState('## Hello, World!\n')

  const handleDocChange = React.useCallback((newDoc) => {
    setDoc(newDoc)
  }, [])

  return (
    <React.Fragment>
      <Head>
        <title>Markdown Editor</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/Markdown Guide.svg' />
      </Head>
      <div className='main-wrapper'>
        <Editor onChange={handleDocChange} initialDoc={doc} />
        <Preview doc={doc} />
      </div>
    </React.Fragment>
  )
}
